repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-ast
  - id: check-docstring-first
  - id: end-of-file-fixer
  - id: trailing-whitespace
# - repo: https://github.com/pycqa/flake8
#   rev: 4.0.1
#   hooks:
#   - id: flake8
#     additional_dependencies: [flake8-typing-imports==1.12.0]
#     args: ['--max-line-length=110']
# - repo: https://github.com/asottile/reorder_python_imports
#   rev: v3.0.1
#   hooks:
#   - id: reorder-python-imports
#     args: [--py3-plus]
# # - repo: https://github.com/psf/black
# #   rev: 22.1.0
# #   hooks:
# #   - id: black
